# Generated by Django 4.2.5 on 2023-09-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customorder_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='pro_forma',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pro_forma',
            name='payment_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Payment ID'),
        ),
        migrations.AddField(
            model_name='pro_forma',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method'),
        ),
    ]
