# Generated by Django 4.2.5 on 2023-09-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customorder_processed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_forma',
            name='client_reaction',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pro_forma',
            name='custom_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='main.customorder', verbose_name='Custom Order'),
        ),
        migrations.AlterField(
            model_name='pro_forma',
            name='status',
            field=models.CharField(choices=[('Doable', 'Doable'), ('Undoable', 'Undoable')], max_length=20, verbose_name='Status'),
        ),
    ]
