# Generated by Django 4.2.5 on 2023-09-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customorder_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_forma',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment ID'),
        ),
    ]
