# Generated by Django 4.2.5 on 2023-09-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pro_forma_client_reaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_forma',
            name='client_reaction',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('None', 'None')], default='Pending', max_length=20, verbose_name='Client Reaction'),
        ),
    ]
