# Generated by Django 4.2.5 on 2023-09-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pro_forma_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_forma',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment ID'),
        ),
    ]
